name: Publish Mod

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x mod/gradlew

    - name: Build with Gradle
      working-directory: ./mod
      run: ./gradlew build
    
    - name: Publish to Maven Repository
      working-directory: ./mod
      env:
        XANDER_MAVEN_USER: ${{ secrets.XANDER_MAVEN_USER }}
        XANDER_MAVEN_PASS: ${{ secrets.XANDER_MAVEN_PASS }}
      run: ./gradlew publish
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-artifacts
        path: |
          mod/versions/*/build/libs/*.jar
        if-no-files-found: warn